### ISSUE TITLE
Does not compile with nginx release 1.23.0

### ISSUE THREAD

**Issue by oblivian** [leev/ngx_http_geoip2_module#108]
ngx_http_geoip2_module.c:172:14: error: assignment to ‘ngx_array_t *’ {aka ‘struct <anonymous> *’} from incompatible pointer type ‘ngx_table_elt_t **’ {aka ‘struct ngx_table_elt_s **’} [-Werror=incompatible-pointer-types]

ngx_http_geoip2_module.c:175:58: error: passing argument 3 of ‘ngx_http_get_forwarded_addr’ from incompatible pointer type [-Werror=incompatible-pointer-types]

**Comment by oblivian** [comment]
@leev seems to work perfectly! 😀 And thank you for this awesome module. 🤩
